services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./results/redis_data:/data
    networks:
      - app_network

  web-api:
    image: &image-name zerosignal0101/packet-analysis-tool:v0.3.0
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --workers 4 --bind 0.0.0.0:7956 "src.packet_analysis.app:create_app()"
    volumes: &common-volumes
      - ./raw_data:/packet-analysis/raw_data:ro
      - ./results:/packet-analysis/results
      - ./src:/packet-analysis/src:ro
    ports:
      - "7956:7956"
    depends_on:
      - redis
    networks:
      - app_network

  celery-worker:
    image: *image-name
    command: celery -A src.packet_analysis.celery_app.celery_app worker
    volumes: *common-volumes
    depends_on:
      - redis
    networks:
      - app_network

  celery-beat:
    image: *image-name
    command: >
      sh -c "rm -f $/packet-analysis/celerybeat/celerybeat.pid && # Remove stale pid file
             celery -A src.packet_analysis.celery_app.celery_app beat --schedule=/packet-analysis/celerybeat/celerybeat_schedule"
    volumes:
      - ./raw_data:/packet-analysis/raw_data:ro
      - ./results:/packet-analysis/results
      - ./src:/packet-analysis/src:ro
      - celerybeat_data:/packet-analysis/celerybeat # Use a named volume to persist the schedule
    depends_on:
      - redis

networks:
  app_network:
    driver: bridge

volumes:
  celerybeat_data: # Define the named volume for persistence
