version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app_network

  packet_analysis:
    image: zerosignal0101/packet-analysis-tool:v0.2.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./raw_data:/app/raw_data
      - ./results:/app/results
      - ./results/logs_flask:/app/logs
      - ./src:/app/src
#    environment:
#      - CALLBACK_URL=http://10.180.124.116:18088/api/replay-core/aglAnalysisResult
    ports:
      - "7956:7956"
    depends_on:
      - redis
    networks:
      - app_network

  celery_worker:
    image: zerosignal0101/packet-analysis-tool:v0.2.3
    command: celery -A src.server.celery worker --loglevel=info
    volumes:
      - ./raw_data:/app/raw_data
      - ./results/logs_celery:/app/logs
      - ./results:/app/results
      - ./src:/app/src
    environment:
      - OPENBLAS_NUM_THREADS=4
    depends_on:
      - redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
